sudo: required
services:
  - docker

before_install:
  - docker build -t wetals/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wetals/react-test npm run test -- --coverage

after_success:
  - docker build -t wetals/multi-client ./client
  - docker build -t wetals/multi-nginx ./nginx
  - docker build -t wetals/multi-server ./server
  - docker build -t wetals/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push wetals/multi-client
  - docker push wetals/multi-nginx
  - docker push wetals/multi-server
  - docker push wetals/multi-worker

deploy
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-065756406312
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY